apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-builder
rules:
- apiGroups: ["build.openshift.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["image.openshift.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
