FROM minimal-gpu:latest
# FROM node:14

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt
ENV CMAKE_ARGS="-DLLAMA_CUBLAS=on"
ENV FORCE_CMAKE=1
ENV BANANAS="ARE COOL"
RUN pip install llama-cpp-python==0.2.39

USER root

RUN adduser appuser


WORKDIR /app
RUN git clone https://github.com/aspanner/AIOps

# RUN cd /app/AIOps
# WORKDIR /app
# RUN echo "Current working directory: $(pwd)"
# RUN ls -alh ./AIOps


# RUN cp -r /app/AIOps /opt/app-root/src
# COPY /app/AIOps /opt/app-root/src

RUN mkdir  -p /opt/app-root/src/AIOps

COPY . /opt/app-root/src/AIOps

WORKDIR /opt/app-root/src
RUN echo "Current working directory: $(pwd)"
RUN ls -alh

USER appuser

