FROM minimal-gpu:latest

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt
ENV CMAKE_ARGS="-DLLAMA_CUBLAS=on"
ENV FORCE_CMAKE=1
ENV BANANAS="ARE COOL"
RUN pip install llama-cpp-python==0.2.39

# WORKDIR /opt/app-root/src
# RUN git clone https://github.com/aspanner/AIOps

# RUN mv /AIOps /opt/app-root/src



# RUN echo ls /opt/app-root/src/AIOps


WORKDIR /app
RUN git clone https://github.com/aspanner/AIOps

