FROM minimal-gpu:latest

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt
ENV CMAKE_ARGS="-DLLAMA_CUBLAS=on"
ENV FORCE_CMAKE=1
ENV BANANAS="ARE COOL"
RUN pip install llama-cpp-python==0.2.39

USER root

RUN adduser appuser


WORKDIR /app
RUN git clone https://github.com/aspanner/AIOps

RUN cd /app/AIOps
RUN ls -alh


RUN cp -r /app/AIOps /opt/app-root/src

USER appuser

